### ISSUE TITLE
During AWS resource creation, delay while the state of the resource is pending?

### ISSUE THREAD

**Issue by dougtoppin** [kizbitz/train#46]
It may be possible for a race condition to exist during some of the AWS resource creation steps such as while creating a VPC. The race is a creation request was made and the next step attempts to use it before the creation has completed.  I have seen this a few times but not every time. It might be helpful to confirm the resource creation before continuing to the next step.

Two examples from different runs of the error follow

```
$ train -vk
Creating AWS VPC ...
Creating IAM Profile: trainer-vpc ...
IAM profile, role, and policy created ...
Creating VPC: trainer-vpc ...
Creating gateway: trainer-vpc-igw ...
Traceback (most recent call last):
  File "/home/train/bin/train", line 111, in <module>
    process()
  File "/home/train/bin/train", line 74, in process
    vpc.create_vpc()
  File "/home/train/train/vpc/vpc.py", line 431, in create_vpc
    gateway = _create_gateway(conn, vpc)
  File "/home/train/train/vpc/vpc.py", line 63, in _create_gateway
    gateway.add_tag('Name', IGW)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/ec2object.py", line 80, in add_tag
    self.add_tags({key: value}, dry_run)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/ec2object.py", line 97, in add_tags
    dry_run=dry_run
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 4220, in create_tags
    return self.get_status('CreateTags', params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request 
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInternetGatewayID.NotFound</Code><Message>The        internetGateway ID 'igw-1ca13c78' does not exist</Message></Error></Errors>    <RequestID>37129cee-d440-422d-a195-f57480c66922</RequestID></Response>


$ train -vk
Creating AWS VPC ...
Creating IAM Profile: trainer-vpc ...
IAM profile, role, and policy created ...
Creating VPC: trainer-vpc ...
Creating gateway: trainer-vpc-igw ...
Creating route table: trainer-vpc-route-table ...
Configuring network ACL: trainer-vpc-network-acl ...
10.0.0.0/20
Creating subnet: trainer-vpc-us-east-1a ...
10.0.16.0/20
Creating subnet: trainer-vpc-us-east-1c ...
Traceback (most recent call last):
  File "/home/train/bin/train", line 111, in <module>
    process()
  File "/home/train/bin/train", line 74, in process
    vpc.create_vpc()
  File "/home/train/train/vpc/vpc.py", line 434, in create_vpc
    _create_subnets(conn, vpc, route_table)
  File "/home/train/train/vpc/vpc.py", line 96, in _create_subnets
    subnet.add_tag('Name', tag)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/ec2object.py", line 80, in add_tag
    self.add_tags({key: value}, dry_run)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/ec2object.py", line 97, in add_tags
    dry_run=dry_run
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 4220, in create_tags
    return self.get_status('CreateTags', params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request 
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidSubnetID.NotFound</Code><Message>The subnet ID     'subnet-49fa6763' does not exist</Message></Error></Errors><RequestID>c4f8c211-5374-433c-    b629-7d6497182137</RequestID></Response>
```

**Comment by kizbitz** [comment]
Closing - Fixed with: https://github.com/kizbitz/train/pull/47
