### ISSUE TITLE
Need a graceful recovery from failed -kv

### ISSUE THREAD

**Issue by mikegcoleman** [kizbitz/train#55]
Sometimes when I run train -kv it will fail because it cannot create the VPC, which is reasonable. 

However, even if I switch to a different region where I can create a VPC, and try again. It will fail because the IAM role (I believe) exists from the previous `train -kv`

I haven't found a way to delete the previously failed lab, so the only way I have found to get around this is to go in and create a new lab.

**Comment by dougtoppin** [comment]
If you use train to purge and terminate does that not clean up? I am pretty sure that I have done this to clean up after a fail anything in a vpc create or lab startup

train -p
train -t

**Comment by mikegcoleman** [comment]
I did not try train -p

I did try train -t, and it didn't work.

**Comment by mikegcoleman** [comment]
I tried the -p and didn't seem to work, this is the error text

Creating AWS VPC ...
Creating IAM Profile: npoulton-hol-test ...
Traceback (most recent call last):
  File "/home/train/bin/train", line 111, in <module>
    process()
  File "/home/train/bin/train", line 74, in process
    vpc.create_vpc()
  File "/home/train/train/vpc/vpc.py", line 462, in create_vpc
    create_iam_profile()
  File "/home/train/train/vpc/vpc.py", line 265, in create_iam_profile
    instance_profile = conn.create_instance_profile(IAM_PROFILE)
  File "/usr/local/lib/python2.7/site-packages/boto/iam/connection.py",
line 1103, in create_instance_profile
    return self.get_response('CreateInstanceProfile', params)
  File "/usr/local/lib/python2.7/site-packages/boto/iam/connection.py",
line 102, in get_response
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 409 Conflict
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>EntityAlreadyExists</Code>
    <Message>Instance Profile npoulton-hol-test already exists.</Message>
  </Error>
  <RequestId>3ccca257-28ee-11e6-a120-7113b0af4e40</RequestId>
</ErrorResponse>

**Comment by dougtoppin** [comment]
On the purge and terminate, did you try them using the same configuration (train.env) right after the fail or after the switch to a new region?

If you use exactly the same train.env file it should be able to clean up (I think) and I think the order should be purge and then terminate.

**Comment by kizbitz** [comment]
Confirmed with multiple VPC's in different regions.

This profile error will also happen if you happen to delete the VPC from the UI. It will delete all of the VPC objects but leave the role profile.

To fix this in the meantime:
- From the AWS Dashboard use one of the 'IAM' or 'Identity & Access Management' links
- Select 'Roles' from the side menu
- Select the Role/Profile and delete

Fix:
- Add the current region to role names to differentiate
- During VPC creation, check for existing role and if it exists, prompt to overwrite/skip
