### ISSUE TITLE
error on vpc creation: Signature expired ...  is now earlier than ...

### ISSUE THREAD

**Issue by dougtoppin** [kizbitz/train#86]
I pulled the current train, followed the train.env setup and am having this problem when trying to create the vpc using macOS Sierra, 10.12.3 with Python 2.7.10
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true

$ docker run -ti --rm --env-file='train.env' -v $(pwd):/host kizbitz/train
dtoppin-:us-east-1:~$ train -vk
Creating AWS VPC ...
Creating IAM Profile: dtoppin-train ...
Traceback (most recent call last):
  File "/home/train/bin/train", line 111, in <module>
    process()
  File "/home/train/bin/train", line 74, in process
    vpc.create_vpc()
  File "/home/train/train/vpc/vpc.py", line 413, in create_vpc
    create_iam_profile()
  File "/home/train/train/vpc/vpc.py", line 216, in create_iam_profile
    instance_profile = conn.create_instance_profile(IAM_PROFILE)
  File "/usr/local/lib/python2.7/site-packages/boto/iam/connection.py", line 1103, in create_instance_profile
    return self.get_response('CreateInstanceProfile', params)
  File "/usr/local/lib/python2.7/site-packages/boto/iam/connection.py", line 102, in get_response
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>Signature expired: 20170126T231538Z is now earlier than 20170127T140819Z (20170127T142319Z - 15 min.)</Message>
  </Error>
  <RequestId>2650f699-e49c-11e6-b0b7-0fd64c3b88b3</RequestId>
</ErrorResponse>

**Comment by dougtoppin** [comment]
A docker restart corrected the issue.
