### ISSUE TITLE
error during  'Creating subnet' Value (us-east-1d) for parameter availabilityZone is invalid

### ISSUE THREAD

**Issue by dougtoppin** [kizbitz/train#87]
During vpc creation I got the following error. Note that subnets 1a-1c were successfully created

Creating route table: dtoppin-train-route-table ...
Configuring network ACL: dtoppin-train-network-acl ...
10.0.0.0/20
Creating subnet: dtoppin-train-us-east-1a ...
10.0.16.0/20
Creating subnet: dtoppin-train-us-east-1b ...
10.0.32.0/20
Creating subnet: dtoppin-train-us-east-1c ...
10.0.48.0/20
Creating subnet: dtoppin-train-us-east-1d ...
Traceback (most recent call last):
  File "/home/train/bin/train", line 111, in <module>
    process()
  File "/home/train/bin/train", line 74, in process
    vpc.create_vpc()
  File "/home/train/train/vpc/vpc.py", line 419, in create_vpc
    _create_subnets(conn, vpc, route_table)
  File "/home/train/train/vpc/vpc.py", line 107, in _create_subnets
    availability_zone=zone)
  File "/usr/local/lib/python2.7/site-packages/boto/vpc/__init__.py", line 1181, in create_subnet
    return self.get_object('CreateSubnet', params, Subnet)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Value (us-east-1d) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1a, us-east-1c, us-east-1b, us-east-1e.</Message></Error></Errors><RequestID>6b7ac7b9-0f3b-408a-bde5-60b011b9f35d</RequestID></Response>

**Comment by dougtoppin** [comment]
I duplicated this issue over a couple of additional runs. I checked for subnets that are available in us-east-1 and got the following back. I am wondering if this is an overlap issue but that is not the specific error being returned.

$ aws ec2 describe-subnets --region=us-east-1 | egrep '.AvailabilityZone|CidrBlock'
            "AvailabilityZone": "us-east-1a",
            "CidrBlock": "10.0.0.0/20",
            "AvailabilityZone": "us-east-1c",
            "CidrBlock": "10.0.32.0/20",
            "AvailabilityZone": "us-east-1b",
            "CidrBlock": "10.0.16.0/20",
            "AvailabilityZone": "us-east-1e",
            "CidrBlock": "10.0.0.0/24",

**Comment by dougtoppin** [comment]
A followup on this issue. For lab environments is it really necessary to use multiple AZs? That may not be necessary for this usage.
